### ISSUE TITLE
Discussion: Adding default styles for form elements

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#484]
**Description**
The Gutenberg PR to add the form inputs to _theme.json elements_ was not completed in time for WordPress 6.7 Beta 1.
Should the theme add default styles for form inputs?

The search and comment forms are already styled.
Login/logout block is not styled:  It can be improved, but needs custom CSS since the expected class names for the button style etc. is missing (this is a known issue).
![image](https://github.com/user-attachments/assets/fe696550-7c55-475b-9df1-d2ef4920239f)

Many forms in third-party plugins and custom blocks are not styled.

**Comment by mikemcalister** [comment]
I've been reading through the previous discussions on this and there are a lot of good points for and against. 

Personally, I'm of the mind that **we should** have some sensible fallback styles for inputs. As Carolina mentioned, we already have some for the comment form, so the styles are there.

As users have pointed out, without any styling the form elements look broken or woefully out of place against the backdrop of the otherwise beautiful design. Maybe that's just the designer in me. 🙃

This should be something we can seamlessly transition to theme.json powered styles when they are available.

**Comment by justintadlock** [comment]
The fix for the login form is just a few lines of CSS: https://github.com/WordPress/gutenberg/issues/50466#issuecomment-1612136221

☝ I've also shared a fix for applying the `.wp-element-button` class to the login form button in that ticket too.

**Comment by carolinan** [comment]
Since it is not a bug introduced in 6.7, I am not sure an update to login/out can be included now, even if someone was able to work on it.

**Comment by evrpress** [comment]
+1 for adding some fallback styles. Things to consider:

**The fallback is for this theme only** 
This would be only for the current theme so others could copy this approach.

**Form plugins often bring their own styles therefore fallback should be minimal with low specificity**
There are not many forms in core but almost every website uses forms. Using a low specificity should prevent any significant issues.

**Comment form styles should be used**
I see no reason why the existing style from the comment form shouldn't be used.

## Discussions

There are already discussions/pr going on
https://github.com/WordPress/gutenberg/issues/29167
https://github.com/WordPress/gutenberg/issues/34198
https://github.com/WordPress/gutenberg/pull/51337

Specific CSS can be found on the post-comment-form block [here](https://github.com/WordPress/gutenberg/blob/75c2147b96086d4d502b652a4a49bdc372bde33f/packages/block-library/src/post-comments-form/style.scss#L2C1-L14C2) and [here](https://github.com/WordPress/gutenberg/blob/75c2147b96086d4d502b652a4a49bdc372bde33f/packages/block-library/src/post-comments-form/style.scss#L49-L58)

## Approach

I would add default styling with a low specificity by using the `:where` pseudo selector:

```  CSS
:where(textarea),
:where(select),
:where(input:not([type="submit"])) {
    border: 1px solid;
    font-size: 1em;
    font-family: inherit;
    border-radius: .25rem;
    border-color: var(--wp--preset--color--accent-6);
}
:where(textarea),
:where(select),
:where(input:not([type="submit"]):not([type="checkbox"])) {
    padding: calc(0.667em + 2px);
}
```

This can be added to the style.css meanwhile until we have [form elements](https://github.com/WordPress/gutenberg/issues/29167) in core

| without CSS | with CSS |
| --- | --- |
| ![Image](https://github.com/user-attachments/assets/26083963-5ea6-44bc-9be6-78dc4a5dcc17) | ![Image](https://github.com/user-attachments/assets/685e90de-15da-4094-8af3-eb9e763eca6c) |

It is still not perfect but I think a good starting point to bring CSS to forms in TT5.

**Comment by troychaplin** [comment]
What if the example from @evrpress was slightly updated to follow the style of the search block?

```css
:where(textarea),
:where(select),
:where(input:not([type="submit"])) {
    border: 1px solid;
    font-size: 1em;
    font-family: inherit;
    border-radius: 3.125rem;
    border-color: var(--wp--preset--color--accent-6);
}

:where(textarea),
:where(select),
:where(input:not([type="submit"]):not([type="checkbox"])) {
		padding: 0.667rem;
}
```

![Image](https://github.com/user-attachments/assets/4e5d67ca-bfa1-4717-ade3-1f24fe92eec1)
