### ISSUE TITLE
Outline styles broken and missing padding

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/twentytwentyfive#595]
**Description**
If you navigate via keyboard you see the focus styles for the navigation and in the main menu there is missing some padding. Also in submenus the bottom outline is hidden, looks broken.

**Screenshots**
![Image](https://github.com/user-attachments/assets/e2706c77-4528-491e-94a8-b9863bbd1faa)
![Image](https://github.com/user-attachments/assets/2bee94ff-05c6-433c-a4c0-3429135cb96a)

**Environment info**
 - Device: MacBook Pro
 - OS: macOS 12.7.6
 - Browser: Firefox 
 - Version: 131.0.3 (aarch64)

**Comment by carolinan** [comment]
I am getting a different result in Chrome, this seems to be a browser issue.

Adding padding on the link itself would break the design in other ways, including breaking the position of the arrow icons.
The focus on the link and the arrow button needs to remain separate, depending on which block setting is enabled.

**Comment by elbsegler63** [comment]
I was able to reproduce the error with both Firefox and Chrome browsers. 
It is in the submenu of a navigation when it is expanded. As shown in the screenshot above.

- Device: Laptop Microsoft
- OS: Windows 11
- Browser 1: Firefox 132.0bß
- Browser 2: Chrome 129

**Comment by Zodiac1978** [comment]
The missing bottom outline in the submenus (second screenshot) could be fixed with this CSS:

```css
.wp-block-navigation .wp-block-navigation-item {
  margin-bottom: 2px;
}
```

This bug is also in Chrome 129 (macOS 12.7.6)

**Comment by Zodiac1978** [comment]
The missing padding could be fixed with adding an offset (for example 4px):

```css
:where(.wp-site-blocks *:focus) {
    outline-width: 2px;
    outline-style: solid;
    outline-offset: 4px;
}
```
